New TextArea component
safetythird-ru/unexistingbooksreviews pull request #14
Opened 2021-12-11 12:54 UTC by yagushevskij

Компонент для вывода полей ввода типа textarea.
Пример использования:
`<TextArea type='text' placeholder='Please, input text' value='Текст' onChange={(e) => console.log(e)} errorText='error text'/>`

2021-12-11 14:12 UTC, goldim commented on src/components/field/text-area/text-area.js
> +const TextArea = ({ labelName, type, placeholder, onChange, name, value, disabled, errorText }) => {
Хотелось бы чтобы данный компонент был немного похож на html. Там значение передается не как атрибут а как содержимое. То есть перенести атрибут value в children.

2021-12-11 14:13 UTC, goldim requested changes
Переименовать главный файл в индекс. Плюс поправка по интерфейсу компонента с содержимым значением.

2021-12-11 17:22 UTC, yagushevskij commented on src/components/field/text-area/text-area.js
> +const TextArea = ({ labelName, type, placeholder, onChange, name, value, disabled, errorText }) => {
Какое это несет преимущество?

2021-12-11 17:25 UTC, yagushevskij commented
> Переименовать главный файл в индекс. Плюс поправка по интерфейсу компонента с содержимым значением.
Для соблюдение единого стиля в проекте будет лучше не использовать index в папках с компонентами.

2021-12-12 10:50 UTC, goldim approved these changes

2021-12-12 16:04 UTC, merged