Refactoring register.js
safetythird-ru/unexistingbooksreviews pull request #2
Opened 2021-11-01 14:21 UTC by yagushevskij

Перевел компонент на функциональный стиль, исправил предупреждение:

> Warning: A component is changing an uncontrolled input of type text to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info:

Так же пропала ошибка при переключении на регистрацию со страницы авторизации (А может быть ее и не было ? :)).

2021-11-01 19:19 UTC, goldim commented on src/components/register/register.js
> +                    value={username || ''}
username передается как свойство (при деструктуризации объекта) может стоит там задать значение по умолчанию. https://stackoverflow.com/questions/63586112/how-to-set-the-default-value-to-props

2021-11-01 19:19 UTC, goldim commented on src/components/register/register.js
> +                    value={email || ''}
тоже самое

2021-11-01 19:20 UTC, goldim commented on src/components/register/register.js
> +                    value={password || ''}
то же самое

2021-11-01 19:21 UTC, goldim commented on src/components/App.js
> +import Register from '../components/register/register';
я бы пока не спешил с папками для каждого компонента пока не будут созданы подкомпоненты

2021-11-01 19:22 UTC, goldim commented on src/components/Register.old.js
> +class Register extends React.Component {
смысл хранить файл со старым кодом?

2021-11-01 19:24 UTC, goldim commented on src/components/register/register.js
> +const Register = ({ onUnload, onChange, onSubmit, username, email, password, errors, inProgress }) => {
пока оставил бы файл Register файл на уровне выше и внес туда бы изменения чтобы можно было видеть отличия в строках, но поэтому моменту не уверен как правильно

2021-11-01 19:37 UTC, goldim requested changes
Поправить или обсудить правильность

2021-11-02 07:43 UTC, yagushevskij commented on src/components/register/register.js
> +                    value={username || ''}
Отличная идея, надо поправить

2021-11-02 07:45 UTC, yagushevskij commented on src/components/App.js
> +import Register from '../components/register/register';
А что, если подкомпоненты создавать внутри родительских компонентов, т.е. в данном случае /register ?

2021-11-02 07:49 UTC, yagushevskij commented on src/components/Register.old.js
> +class Register extends React.Component {
На каком - то из созвонов по проектной кухне Григорий предложил добавлять префиксы к старым файлам и не удалять их пока. Я пока что не знаю для чего это, но никто не был против :)

2021-11-02 09:16 UTC, goldim commented on src/components/Register.old.js
> +class Register extends React.Component {
Понял, надо будет узнать зачем

2021-11-02 09:20 UTC, goldim commented on src/components/App.js
> +import Register from '../components/register/register';
Да, так и будет с большими компонентами, но можно пока не спешить поправки внести в этот файл чтобы были видны отличия. Не придирка, предложение.

2021-11-02 09:23 UTC, goldim reviewed
Из всех замечаний и предложений, ток поправить первое поправить с передачей значения по умолчанию после одобряю запрос

2021-11-02 09:51 UTC, yagushevskij commented
Хм, пытаюсь запушить изменения, но получаю в ответ такое:

> fatal: 'origin/refactoring_Register.js' does not appear to be a git repository
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.

Есть у кого догадки, почему вдруг стало нельзя вносить изменения?

2021-11-02 09:56 UTC, goldim approved these changes

2021-11-06 12:59 UTC, yagushevskij commented on src/components/register/register.js
> +  onChange: (name, value) => dispatch({ type: UPDATE_FIELD_AUTH, key: name, value }),
Может быть стоит хранить набираемый текст в state компонента? И лишь по сабмиту отправлять данные в redux.
@goldim @BatradzSanakoev @Vinorval @reachoutfaith

2021-11-06 12:59 UTC, yagushevskij commented on src/agent.js
> +    requests.post('/users', { user: data }),
Кажется лучше принимать данные объектом. Таким образом можно не заботится о порядке аргументов функции.

2021-11-06 12:59 UTC, yagushevskij commented on src/components/register/register.js
> +    const payload = agent.Auth.register(data);
Соответственно и передавать объект, вместо отдельных аргументов

2021-11-07 16:41 UTC, smuravyev commented on src/components/register/register.js
> +            <form onSubmit={submitForm(data)}>
А зачем передавать в submitForm что-то? Вроде как объявление выше гласит 

`const submitForm = () => ev => {`

Да и data у нас и так в области видимости функции submitForm?

2021-11-07 23:29 UTC, smuravyev commented on src/components/register/register.js
> +  onUnload: () => dispatch({ type: REGISTER_PAGE_UNLOADED })
В ПР 3 - https://yandex-students.slack.com/archives/C02GYUF09L2/p1636323494054700 лежит конфиг, в котором нормально работают useDispatch и useSelector. Есть предложение переписать mapStateToProps/mapDispatchToProps на хуках, что думаете на этот счет?

2021-11-08 07:35 UTC, yagushevskij commented on src/components/register/register.js
> +  onUnload: () => dispatch({ type: REGISTER_PAGE_UNLOADED })
С useDispatch и useSelector код будет лаконичней и понятней, на мой взгляд. Хорошая идея.

2021-11-08 07:38 UTC, yagushevskij commented on src/components/register/register.js
> +            <form onSubmit={submitForm(data)}>
Да, что - то я перемудрил. Глаз - алмаз!

2021-11-08 07:38 UTC, BatradzSanakoev commented on src/components/register/register.js
> +  onUnload: () => dispatch({ type: REGISTER_PAGE_UNLOADED })
учитывая, что мы собираемся каждый компонент на функционалку перевести, то актуальная мысль

2021-12-07 10:27 UTC, goldim commented on src/components/register/register.js
> +  onUnload: () => dispatch({ type: REGISTER_PAGE_UNLOADED })
Да, будет лаконичнее если компоненты будут необъемными в плане кода

2021-12-07 10:28 UTC, goldim commented
Не понимаю, почему данный PR не слит?

2021-12-07 10:29 UTC, goldim commented on src/components/register/register.js
> +  onChange: (name, value) => dispatch({ type: UPDATE_FIELD_AUTH, key: name, value }),
Уже обсуждали что данные форм лучше не хранить в хранилище

2021-12-09 08:07 UTC, closed without merging